version: "3"
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: comunicacaodb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    container_name: comunicacaodb
  modulo-comunicacao:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb