version: "3"
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: comunicacaodb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    container_name: comunicacaodb
  modulo-comunicacao:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000